-- ===============================
-- 0) CLEANUP: drop existing objects if they exist
-- ===============================
BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION get_book_by_barcode';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_book_info';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_borrows_status_upd';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_books_upd_ts';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_categories_count';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_categories_upd_ts';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE download_logs CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE borrows CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE books CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE categories CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- ===============================
-- 1) USERS
-- ===============================
CREATE TABLE users (
  user_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username  VARCHAR2(50) UNIQUE NOT NULL,
  password  VARCHAR2(100) NOT NULL,
  role      VARCHAR2(10) NOT NULL
             CONSTRAINT chk_users_role
               CHECK (role IN ('ADMIN','USER'))
);

-- ===============================
-- 2) CATEGORIES
-- ===============================
CREATE TABLE categories (
  category_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  category_name  VARCHAR2(100) UNIQUE NOT NULL,
  description    CLOB,
  book_count     NUMBER DEFAULT 0 NOT NULL,
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Trigger: update updated_at on categories
CREATE OR REPLACE TRIGGER trg_categories_upd_ts
  BEFORE UPDATE ON categories
  FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- Trigger: maintain book_count in categories
CREATE OR REPLACE TRIGGER trg_categories_count
  AFTER INSERT OR DELETE ON books
  FOR EACH ROW
DECLARE
  v_delta PLS_INTEGER;
BEGIN
  IF INSERTING THEN
    v_delta := 1;
  ELSIF DELETING THEN
    v_delta := -1;
  END IF;
  UPDATE categories
     SET book_count = book_count + v_delta
   WHERE category_id = NVL(:NEW.category_id, :OLD.category_id);
END;
/

-- ===============================
-- 3) BOOKS
-- ===============================
CREATE TABLE books (
  book_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  category_id  NUMBER NOT NULL
                CONSTRAINT fk_books_cat
                  REFERENCES categories(category_id),
  barcode      VARCHAR2(50) UNIQUE NOT NULL,
  title        VARCHAR2(200) UNIQUE NOT NULL,
  author       VARCHAR2(200),
  description  CLOB,
  cover_image  BLOB,
  pdf_file     BLOB,
  total_copies NUMBER DEFAULT 1 NOT NULL,
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Trigger: update updated_at on books
CREATE OR REPLACE TRIGGER trg_books_upd_ts
  BEFORE UPDATE ON books
  FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- ===============================
-- 4) BORROWS
-- ===============================
CREATE TABLE borrows (
  borrow_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id     NUMBER NOT NULL
               CONSTRAINT fk_borrows_user
                 REFERENCES users(user_id),
  book_id     NUMBER NOT NULL
               CONSTRAINT fk_borrows_book
                 REFERENCES books(book_id),
  borrow_date DATE DEFAULT SYSDATE NOT NULL,
  duration    NUMBER DEFAULT 14 NOT NULL,
  return_date DATE,
  due_date    DATE GENERATED ALWAYS AS (borrow_date + duration) VIRTUAL,
  total_days  NUMBER GENERATED ALWAYS AS (
                  CASE WHEN return_date IS NOT NULL
                       THEN return_date - borrow_date
                       ELSE NULL END
               ) VIRTUAL,
  status      VARCHAR2(10) DEFAULT 'BORROWED' NOT NULL
               CONSTRAINT chk_borrows_status
                 CHECK (status IN ('BORROWED','RETURNED','OVERDUE'))
);

-- Trigger: set status on borrows
CREATE OR REPLACE TRIGGER trg_borrows_status_upd
  BEFORE INSERT OR UPDATE ON borrows
  FOR EACH ROW
BEGIN
  IF :NEW.return_date IS NOT NULL THEN
    :NEW.status := 'RETURNED';
  ELSIF SYSDATE > :NEW.due_date THEN
    :NEW.status := 'OVERDUE';
  ELSE
    :NEW.status := 'BORROWED';
  END IF;
END;
/

-- ===============================
-- 5) DOWNLOAD_LOGS
-- ===============================
CREATE TABLE download_logs (
  download_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id       NUMBER NOT NULL
                 CONSTRAINT fk_dl_user
                   REFERENCES users(user_id),
  book_id       NUMBER NOT NULL
                 CONSTRAINT fk_dl_book
                   REFERENCES books(book_id),
  downloaded_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ===============================
-- 6) VIEW: full book info + availability
-- ===============================
CREATE OR REPLACE VIEW vw_book_info AS
SELECT
  b.barcode,
  c.category_name,
  b.title,
  b.author,
  b.description,
  b.total_copies,
  NVL(a.borrowed_count, 0) AS borrowed_count,
  b.total_copies - NVL(a.borrowed_count, 0) AS available_copies,
  b.created_at,
  b.updated_at
FROM books b
JOIN categories c ON b.category_id = c.category_id
LEFT JOIN (
  SELECT book_id,
         SUM(CASE WHEN status = 'BORROWED' THEN 1 ELSE 0 END) AS borrowed_count
    FROM borrows
   GROUP BY book_id
) a ON b.book_id = a.book_id;

-- ===============================
-- 7) FUNCTION: fetch book by barcode
-- ===============================
CREATE OR REPLACE FUNCTION get_book_by_barcode (
  p_barcode IN VARCHAR2
) RETURN SYS_REFCURSOR IS
  rc SYS_REFCURSOR;
BEGIN
  OPEN rc FOR
    SELECT * FROM vw_book_info WHERE barcode = p_barcode;
  RETURN rc;
END;
/


-- ================================================
-- 1) Package specification
-- ================================================
CREATE OR REPLACE PACKAGE category_pkg AS

  -- Create a new category
  PROCEDURE add_category(
    p_name        IN VARCHAR2,
    p_description IN CLOB
  );

  -- Read a single category by ID
  PROCEDURE get_category(
    p_id           IN  NUMBER,
    p_name         OUT VARCHAR2,
    p_description  OUT CLOB,
    p_count        OUT NUMBER,
    p_created_at   OUT TIMESTAMP,
    p_updated_at   OUT TIMESTAMP
  );

  -- List all categories (returns a REF CURSOR)
  PROCEDURE list_categories(
    p_cursor OUT SYS_REFCURSOR
  );

  -- Update an existing category
  PROCEDURE update_category(
    p_id           IN NUMBER,
    p_name         IN VARCHAR2,
    p_description  IN CLOB
  );

  -- Delete a category
  PROCEDURE delete_category(
    p_id IN NUMBER
  );

END category_pkg;
/

-- ================================================
-- 2) Package body
-- ================================================
CREATE OR REPLACE PACKAGE BODY category_pkg AS

  PROCEDURE add_category(
    p_name        IN VARCHAR2,
    p_description IN CLOB
  ) IS
  BEGIN
    INSERT INTO categories(category_name, description)
    VALUES(p_name, p_description);
    COMMIT;
  END add_category;


  PROCEDURE get_category(
    p_id           IN  NUMBER,
    p_name         OUT VARCHAR2,
    p_description  OUT CLOB,
    p_count        OUT NUMBER,
    p_created_at   OUT TIMESTAMP,
    p_updated_at   OUT TIMESTAMP
  ) IS
  BEGIN
    SELECT category_name,
           description,
           book_count,
           created_at,
           updated_at
      INTO p_name,
           p_description,
           p_count,
           p_created_at,
           p_updated_at
      FROM categories
     WHERE category_id = p_id;
  END get_category;


  PROCEDURE list_categories(
    p_cursor OUT SYS_REFCURSOR
  ) IS
  BEGIN
    OPEN p_cursor FOR
      SELECT category_id,
             category_name,
             description,
             book_count,
             created_at,
             updated_at
        FROM categories
       ORDER BY category_id;
  END list_categories;


  PROCEDURE update_category(
    p_id           IN NUMBER,
    p_name         IN VARCHAR2,
    p_description  IN CLOB
  ) IS
  BEGIN
    UPDATE categories
       SET category_name = p_name,
           description   = p_description,
           updated_at    = SYSTIMESTAMP
     WHERE category_id = p_id;
    COMMIT;
  END update_category;


  PROCEDURE delete_category(
    p_id IN NUMBER
  ) IS
  BEGIN
    DELETE FROM categories
     WHERE category_id = p_id;
    COMMIT;
  END delete_category;

END category_pkg;
/
